### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by revenz** [revenz/NextPvrWebConsole#25]
as a user I would like to be able to reset my password if I have forgotten it.

This would be done on a "Forgot Password" link on the login screen, where it will email me a password reset link to my email address, from there I will be able to set a new password.

**Comment by revenz** [comment]
having some issues with sending emails, may have to find a default free smtp server that works for most people.  

will need to also encrypt the auth password safely in the database where itcannot be decrypted if someone gets a copy of that database... perhaps using a machine serial number as a seed.

**Comment by KaraokeStu** [comment]
I would suggest using a key and some form of web service, otherwise using something like the gmail server (with the project having its own gmail account)

**Comment by revenz** [comment]
my preferred solution is a internal smtp server which will send the emails without the user having to configure anything.  as long as their port 25 it should work.   though some users may want to specify a specific smtp server so will allow for that.

just trying to find some code that sends smtp from localhost reliable and that is free....

putting this on the back burner for now and going to concentrate on other areas, i'll make it so it logs the reset url into a log file, so if smtp isnt working they can get the url from a log file.   

however this will still need to be properly fixed before the alpha release

**Comment by revenz** [comment]
this is closed, works if email is sent, leaving smtp settings ticket open for the emailer part
