### ISSUE TITLE
It would be good to see extra information from the recording view

### ISSUE THREAD

**Issue by KaraokeStu** [revenz/NextPvrWebConsole#30]
I would like to see the following information:

Programme/Episode Title
Synopsis
Episode number (if available)
Subtitles
Sign Language
Repeat

**Comment by revenz** [comment]
will only show the same information as the core NextPVR gui, if that doesnt show this info this console will not either.

however if any of the fields are missing that the NextPVR gui shows, then I will add those.

**Comment by KaraokeStu** [comment]
The current NEWA system shows the information against the recording (taken from the TV guide I believe)

e.g:

"The Work Experience" - 18 November 2012 03:08 - 03:40 - E4
A new reality comedy series based in the madness of a fashion PR agency. Two ambitious interns, Brave and Danni, embark on a challenging week of tasks, unaware that it's all a big set-up. [S]
