### ISSUE TITLE
Cross Browser Support

### ISSUE THREAD

**Issue by KaraokeStu** [revenz/NextPvrWebConsole#31]
This is more a placeholder ticket and is not meant to be for the Alpha Release.

The interface should function in the following main browsers:

IE9/10 (will try and support basic ie8 if possible as well)
Chrome (this is the standard browser which all the majority of testing will be done against)
Firefox 
Safari (wont be officially supported, usage is less than 6% - 10% of the world)
Opera (wont be officially supported, usage is less than 2% of the world)

**Comment by revenz** [comment]
supported browsers officially are
Chrome Latest
Firefox Latest
IE 9 and 10
